version: "3.9"

services:
  app:
    container_name: autstore
    image: autstore
    build: 
      context: . #путь до докерфайла
      dockerfile: Dockerfile #Сам файл
      target: autstore #этап FROM в Dockerfile 
    restart: always
    environment:
      API_SERVER_ADDR: ":8000"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    links: #связывает контейнер app контейнером db
      - db
    depends_on: #ожидаем запуска образа базы
      - db
  db:
    # image: postgres:14-bullseye #последняя 14.9
    container_name: autstore-db
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  postgres_data: